version: "3"
services:
  sku-usage-api-php-client:
    image: europe-docker.pkg.dev/dk-gg-rgstry/base/php:dev-linux
    container_name: bb_sku_usage_api_php_client
    volumes:
      - ./:/var/www
    working_dir: /var/www
