version: "3"
services:
  bb-sku-usage-api-php-client:
    image: europe-docker.pkg.dev/dk-gg-rgstry/base/php:dev-linux
    container_name: bb_sku_usage_api_php_client
    volumes:
      - ./:/var/www
    working_dir: /var/www
    ports:
      - "30280:3000"
    environment:
      VALID_TOKEN_ADD: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI5MzQ5OGZhMy1hMDI5LTQ3NGUtODNlYy1iM2ZjZjIyYzhjZGYiLCJqdGkiOiJmMjc4Mzc2YTk0YjFlYWE0MTg0YmRiZWQ3ODc3N2JhMmE0YTRmOTY2YjhjNDE5MGZkZDYyMGVhMTBmMGZhNmFjYTQ1ZDBmNzUzMzZjNTAzOCIsImlhdCI6MTYxOTQ0MTY2Ni4yMjIyNTEsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjMwMjUwIiwibmJmIjoxNjE5NDQxNjY2LjIyMjI1MSwiZXhwIjo0Nzc1MTE1MjY2LjIyMjI1MSwic3ViIjoiIiwic2NvcGVzIjpbInNrdS11c2FnZTphZGQiXX0.msKTlW8MId18q_YlrjWgiJl_XNEITrcYT4kcAgzNQXBQq3xIi50E6w-GCNH9X--cbhHR15AuU8Zt0RJ94OcDRA
      VALID_TOKEN_READ: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI5MzQ5OGZhMy1hMDI5LTQ3NGUtODNlYy1iM2ZjZjIyYzhjZGYiLCJqdGkiOiI2MzQ4NDVkOWM5ZDE3YTg1MjU1YWMxMjllZWU1NzE0NDU0MzE0NzE1ZTY0NWM2M2QxY2VlMDZkMDU5MGViNDQ4M2ZkOWI5M2ZjNGY0YzM5MiIsImlhdCI6MTYxOTQ0MTU5MS43MTM0MTYsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjMwMjUwIiwibmJmIjoxNjE5NDQxNTkxLjcxMzQxNiwiZXhwIjo0Nzc1MTE1MTkxLjcxMzQxNiwic3ViIjoiIiwic2NvcGVzIjpbInNrdS11c2FnZTpyZWFkIl19.qYQqPVKxrFbbukj6yipjA1c1BBUavtjMRjBvKiMLo8AR-mG9ULnkb7zLyDJGeotuxR7r6UkgIUj9zcxto8ZkAA
      VALID_TOKEN_EDIT: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI5MzQ5OGZhMy1hMDI5LTQ3NGUtODNlYy1iM2ZjZjIyYzhjZGYiLCJqdGkiOiI4N2I5NmE4Y2M0ZDYyYzljZTE2MTVkYWZiOWRkMjc3MzM1YWI2NjRkYzY0ZjQzMjk5ZTUwZjY3NDQwNWM5YzM5ODY4NDcyZDAwNWNiMjA0YiIsImlhdCI6MTYxOTQ0MTY5MS40OTgzNTksImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjMwMjUwIiwibmJmIjoxNjE5NDQxNjkxLjQ5ODM1OSwiZXhwIjo0Nzc1MTE1MjkxLjQ5ODM1OSwic3ViIjoiIiwic2NvcGVzIjpbInNrdS11c2FnZTplZGl0Il19.lbc2MK59k1GcgGlAJEz3GtG8kIWG9GzLpwDKMCPgaqiU1Z1t-EBKafKsQRdRokuW27ql6w43Ayg83wb4kx5lSg
  bb-sku-usage-api-php-client-pact-mock-service:
    image: pactfoundation/pact-cli
    container_name: bb_sku_usage_api_php_client_pact_mock_service
    volumes:
      - ./pacts/:/pacts
    ports:
      - "30287:30287"
    command: [
        "mock-service",
        "--port", "30287",
        "--host", "0.0.0.0",
        "--pact-file-write-mode", "overwrite",
        "--consumer", "skuUsageConsumer",
        "--provider", "skuUsageProvider",
        "--pact-dir", "/pacts"
    ]
