version: 2.1
aliases:
  - &workflow-name-continuous "Continuous Deployment Workflow"
  - &job-name-mirror "Mirror Repository to Github"
  - &branch-main "main"
  - &context-cloud "cloud_deployment"
executors:
  git:
    docker:
      - image: alpine/git:latest
  php-dev:
    docker:
      - image: europe-docker.pkg.dev/dk-gg-rgstry/base/php:dev
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_ACCOUNT
jobs:
  *job-name-mirror :
    executor: git
    steps:
      - checkout:
          name: Checkout source code
      - run:
          name: Mirror the repository to Github
          command: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git remote add github git@github.com:datenkraft/bb-sku-usage-api-php-client.git
            git push github main --tags
workflows:
  version: 2
  *workflow-name-continuous :
    jobs:
      - *job-name-mirror :
          context: *context-cloud
          filters:
            branches:
              only:
                - *branch-main